parameters:
  graphael.environment_prefix: ~
  graphael.debug: '%env(default:false:bool:resolve:%graphael.environment_prefix%DEBUG)%'
  graphael.jwt_algo: '%env(default:RS256:string:resolve:%graphael.environment_prefix%JWT_ALGO)%'
  graphael.jwt_key: '%env(string:resolve:%graphael.environment_prefix%JWT_KEY)%'
  graphael.jwt_username_claim: '%env(string:resolve:%graphael.environment_prefix%JWT_USERNAME_CLAIM)%'
  graphael.jwt_roles_claim: '%env(string:resolve:%graphael.environment_prefix%JWT_ROLES_CLAIM)%'
  graphael.admin_role: '%env(default:ROLE_ADMIN:string:resolve:%graphael.environment_prefix%ADMIN_ROLE)%'
  graphael.jwt_default_role: '%env(string:resolve:%graphael.environment_prefix%JWT_DEFAULT_ROLE)%'
  graphael.cache_driver: '%env(string:resolve:%graphael.environment_prefix%CACHE_DRIVER)%'
  graphael.cache_driver_file_path: '%env(string:resolve:%graphael.environment_prefix%CACHE_DRIVER_FILE_PATH)%'

services:
  LinkORB\Bundle\GraphaelBundle\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  Connector\Connector:

  PDO:

  LinkORB\Bundle\GraphaelBundle\Services\DependencyInjection\ContainerTypeRegistry:
  LinkORB\Bundle\GraphaelBundle\Security\JwtFactory:
  LinkORB\Bundle\GraphaelBundle\Security\Provider\JwtAuthProvider:
  LinkORB\Bundle\GraphaelBundle\Services\Server:
  LinkORB\Bundle\GraphaelBundle\Services\FieldResolver:

  LinkORB\Bundle\GraphaelBundle\Services\DependencyInjection\TypeRegistryInterface: '@LinkORB\Bundle\GraphaelBundle\Services\DependencyInjection\ContainerTypeRegistry'


